// Generated by CoffeeScript 1.10.0
(function() {
    var createJar, createMessage, displayHosts, getAnomaliesRequestParams, getInitialRequestParams, getNewSessionIdRequestParams, getSecurityRequestParams, getSessionId, getXSRFRequestParams, hostName, invokeOpsaApiHandler, ongoing, password, request, requestp, scan, semaphore, updateSemaphore, user;

  createMessage = function(res) {
    var msgData, numHosts, opsa;
    numHosts = res.match[1];
    opsa = JSON.stringify({
            "oa_sysperf_global": [
                {
                    "processedResult": [
                        {
                            "resultType": "singlevalue",
                            "metricName": "AGGREGATE_AVG_oa_sysperf_global_cpu_util",
                            "metricLabel": "CPU Util &#x28;Aggregate avg&#x29;",
                            "metricUnit": "%",
                            "metricDescription": "CPU Util &#x28;Aggregate avg&#x29;",
                            "dimensionValues": [
                                "16.60.188.71"
                            ],
                            "displayDimensionValues": [
                                "16.60.188.71"
                            ],
                            "drillLabel": "host withkey \"16.60.188.71\"",
                            "drillPQL": "host withkey \"16.60.188.71\"",
                            "drillTimeFrame": null,
                            "metricValues": [
                                {
                                    "metricValue": 41.6077777777778,
                                    "computeType": "topn_aggregate_avg"
                                }
                            ]
                        },
                        {
                            "resultType": "singlevalue",
                            "metricName": "TOPN_AGGREGATE_AVG_oa_sysperf_global_cpu_util_10",
                            "metricLabel": "CPU Util &#x28;Aggregate avg&#x29; &#x28;Topn&#x29;",
                            "metricUnit": "",
                            "metricDescription": "CPU Util &#x28;Aggregate avg&#x29; &#x28;Topn&#x29;",
                            "dimensionValues": [
                                "16.60.188.71"
                            ],
                            "displayDimensionValues": [
                                "16.60.188.71"
                            ],
                            "drillLabel": "host withkey \"16.60.188.71\"",
                            "drillPQL": "host withkey \"16.60.188.71\"",
                            "drillTimeFrame": null,
                            "metricValues": [
                                {
                                    "metricValue": 1.0,
                                    "computeType": "topn_aggregate_avg_rank"
                                }
                            ]
                        },
                        {
                            "resultType": "singlevalue",
                            "metricName": "AGGREGATE_AVG_oa_sysperf_global_cpu_util",
                            "metricLabel": "CPU Util &#x28;Aggregate avg&#x29;",
                            "metricUnit": "%",
                            "metricDescription": "CPU Util &#x28;Aggregate avg&#x29;",
                            "dimensionValues": [
                                "opsa-aob2.hpswlabs.adapps.hp.com"
                            ],
                            "displayDimensionValues": [
                                "opsa-aob2.hpswlabs.adapps.hp.com"
                            ],
                            "drillLabel": "host withkey \"opsa-aob2.hpswlabs.adapps.hp.com\"",
                            "drillPQL": "host withkey \"opsa-aob2.hpswlabs.adapps.hp.com\"",
                            "drillTimeFrame": null,
                            "metricValues": [
                                {
                                    "metricValue": 3.06888888888889,
                                    "computeType": "topn_aggregate_avg"
                                }
                            ]
                        },
                        {
                            "resultType": "singlevalue",
                            "metricName": "TOPN_AGGREGATE_AVG_oa_sysperf_global_cpu_util_10",
                            "metricLabel": "CPU Util &#x28;Aggregate avg&#x29; &#x28;Topn&#x29;",
                            "metricUnit": "",
                            "metricDescription": "CPU Util &#x28;Aggregate avg&#x29; &#x28;Topn&#x29;",
                            "dimensionValues": [
                                "opsa-aob2.hpswlabs.adapps.hp.com"
                            ],
                            "displayDimensionValues": [
                                "opsa-aob2.hpswlabs.adapps.hp.com"
                            ],
                            "drillLabel": "host withkey \"opsa-aob2.hpswlabs.adapps.hp.com\"",
                            "drillPQL": "host withkey \"opsa-aob2.hpswlabs.adapps.hp.com\"",
                            "drillTimeFrame": null,
                            "metricValues": [
                                {
                                    "metricValue": 2.0,
                                    "computeType": "topn_aggregate_avg_rank"
                                }
                            ]
                        }
                    ],
                    "filterQueryResult": false,
                    "metricLabels": [
                        "CPU Util &#x28;Aggregate avg&#x29; &#x28;Topn&#x29;",
                        "CPU Util &#x28;Aggregate avg&#x29; &#x28;&#x25;&#x29;"
                    ],
                    "outerCall": false,
                    "partialResult": false,
                    "aggregatePlayback": false,
                    "metaResult": false
                }
            ]
        }
    );
    msgData = {
      text: "Latest changes",
      attachments: [
        {
          fallback: "Comparing 77777",
          title: "Comparing 88988888}",
          title_link: "89988898",
          text: "commits_summary",
          mrkdwn_in: ["text"]
        }
      ]
    };
    return res.robot.emit('slack.attachment', {
      message: {
        "type": "message",
        "channel": "C2147483705",
        "user": "ofer",
        "text": "Hello world",
        "ts": "1355517523.000005",
        "envelope": "envelope"
      },
      content: {
          text: "Alert Test",
          fallback: "Alert fallback",
        fields: [
          {
              title: "Alert Field 1",
              value: "Alert value 1"
          }
        ]
      },
      channel: "#opsa-channel",
      username: "opsa",
      icon_url: "...",
      icon_emoji: "..."
    });
  };

  scan = function(obj, level) {
    var c, fields, k, lineNum, spaces;
    k = void 0;
    if (typeof level === 'undefined') {
      level = 0;
    }
    spaces = '';
    c = 0;
    while (c < level) {
      spaces += ' ';
      c++;
    }
    if (obj instanceof Object) {
      fields = '';
      lineNum = 1;
      for (k in obj) {
        k = k;
        if (obj.hasOwnProperty(k)) {
          fields += spaces + '*' + k + ':*' + scan(obj[k], level + 1) + "\n";
        }
      }
    } else {
      return spaces + "`" + obj + '`\n';
    }
    return fields + '\n';
  };

  displayHosts = function(res) {
    var numHosts, opsa;
    numHosts = res.match[1];
    opsa = JSON.stringify({
            "oa_sysperf_global": [
                {
                    "processedResult": [
                        {
                            "resultType": "singlevalue",
                            "metricName": "AGGREGATE_AVG_oa_sysperf_global_cpu_util",
                            "metricLabel": "CPU Util &#x28;Aggregate avg&#x29;",
                            "metricUnit": "%",
                            "metricDescription": "CPU Util &#x28;Aggregate avg&#x29;",
                            "dimensionValues": [
                                "16.60.188.71"
                            ],
                            "displayDimensionValues": [
                                "16.60.188.71"
                            ],
                            "drillLabel": "host withkey \"16.60.188.71\"",
                            "drillPQL": "host withkey \"16.60.188.71\"",
                            "drillTimeFrame": null,
                            "metricValues": [
                                {
                                    "metricValue": 41.6077777777778,
                                    "computeType": "topn_aggregate_avg"
                                }
                            ]
                        },
                        {
                            "resultType": "singlevalue",
                            "metricName": "TOPN_AGGREGATE_AVG_oa_sysperf_global_cpu_util_10",
                            "metricLabel": "CPU Util &#x28;Aggregate avg&#x29; &#x28;Topn&#x29;",
                            "metricUnit": "",
                            "metricDescription": "CPU Util &#x28;Aggregate avg&#x29; &#x28;Topn&#x29;",
                            "dimensionValues": [
                                "16.60.188.71"
                            ],
                            "displayDimensionValues": [
                                "16.60.188.71"
                            ],
                            "drillLabel": "host withkey \"16.60.188.71\"",
                            "drillPQL": "host withkey \"16.60.188.71\"",
                            "drillTimeFrame": null,
                            "metricValues": [
                                {
                                    "metricValue": 1.0,
                                    "computeType": "topn_aggregate_avg_rank"
                                }
                            ]
                        },
                        {
                            "resultType": "singlevalue",
                            "metricName": "AGGREGATE_AVG_oa_sysperf_global_cpu_util",
                            "metricLabel": "CPU Util &#x28;Aggregate avg&#x29;",
                            "metricUnit": "%",
                            "metricDescription": "CPU Util &#x28;Aggregate avg&#x29;",
                            "dimensionValues": [
                                "opsa-aob2.hpswlabs.adapps.hp.com"
                            ],
                            "displayDimensionValues": [
                                "opsa-aob2.hpswlabs.adapps.hp.com"
                            ],
                            "drillLabel": "host withkey \"opsa-aob2.hpswlabs.adapps.hp.com\"",
                            "drillPQL": "host withkey \"opsa-aob2.hpswlabs.adapps.hp.com\"",
                            "drillTimeFrame": null,
                            "metricValues": [
                                {
                                    "metricValue": 3.06888888888889,
                                    "computeType": "topn_aggregate_avg"
                                }
                            ]
                        },
                        {
                            "resultType": "singlevalue",
                            "metricName": "TOPN_AGGREGATE_AVG_oa_sysperf_global_cpu_util_10",
                            "metricLabel": "CPU Util &#x28;Aggregate avg&#x29; &#x28;Topn&#x29;",
                            "metricUnit": "",
                            "metricDescription": "CPU Util &#x28;Aggregate avg&#x29; &#x28;Topn&#x29;",
                            "dimensionValues": [
                                "opsa-aob2.hpswlabs.adapps.hp.com"
                            ],
                            "displayDimensionValues": [
                                "opsa-aob2.hpswlabs.adapps.hp.com"
                            ],
                            "drillLabel": "host withkey \"opsa-aob2.hpswlabs.adapps.hp.com\"",
                            "drillPQL": "host withkey \"opsa-aob2.hpswlabs.adapps.hp.com\"",
                            "drillTimeFrame": null,
                            "metricValues": [
                                {
                                    "metricValue": 2.0,
                                    "computeType": "topn_aggregate_avg_rank"
                                }
                            ]
                        }
                    ],
                    "filterQueryResult": false,
                    "metricLabels": [
                        "CPU Util &#x28;*Aggregate* avg&#x29; &#x28;Topn&#x29;",
                        "CPU Util &#x28;*Aggregate* avg&#x29; &#x28;&#x25;&#x29;"
                    ],
                    "outerCall": false,
                    "partialResult": false,
                    "aggregatePlayback": false,
                    "metaResult": false
                }
            ]
        }
    );
    return res.reply(("Displaying top " + numHosts + " hosts") + scan(JSON.parse(opsa)));
  };

    request = require('request');

    require('request-debug')(request);

    hostName = '16.60.188.235:8080/opsa';

    user = "opsa";

    password = "opsa";

    semaphore = 0;

    ongoing = false;

    getSessionId = function (res, cookieIndex) {
        var cookie, firstCookie, jSessionId;
        cookie = res.headers["set-cookie"];
        if (typeof cookie === 'undefined') {
            return;
        }
        firstCookie = cookie[cookieIndex];
        return jSessionId = firstCookie.split("=")[1].split(";")[0];
  };

    createJar = function (res, url, cookieIndex) {
        var cookie, jSessionId, jar;
        if (!cookieIndex) {
            cookieIndex = 0;
        }
        jSessionId = getSessionId(res, cookieIndex);
        if (typeof jSessionId === 'undefined') {
            return;
        }
        jar = request.jar();
        cookie = request.cookie('JSESSIONID=' + jSessionId);
        console.log("setting cookie: " + cookie);
        jar.setCookie(cookie, url, function (error, cookie) {
        });
        return jar;
    };

    updateSemaphore = function () {
        var ongoing1;
        ongoing1 = false;
        if (Date.now() - semaphore < 250000) {
            ongoing1 = true;
        }
        semaphore = Date.now();
        return ongoing1;
    };

    getSecurityRequestParams = function (opsaHomeUrl, res) {
        var form, headers, jar, method, url;
        url = opsaHomeUrl + "/j_security_check";
        jar = createJar(res, url, 1);
        method = 'POST';
        form = {
            j_username: user,
            j_password: password
    };
        headers = {
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
            'Accept-Encoding': 'gzip, deflate',
            'Accept-Language': 'en-US,en;q=0.8,he;q=0.6',
            'Connection': 'keep-alive',
            'Content-Type': 'application/x-www-form-urlencoded',
            'Upgrade-Insecure-Requests': '1',
            'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36',
            'Cache-Control': 'max-age=0'
    };
        return {
            method: method,
            url: url,
            jar: jar,
            headers: headers,
            form: form
    };
    };

    getInitialRequestParams = function (opsaHomeUrl) {
        var headers, method, url;
        url = opsaHomeUrl;
        method = 'GET';
        headers = {
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
            'Accept-Encoding': 'gzip, deflate, sdch',
            'Accept-Language': 'en-US,en;q=0.8,he;q=0.6',
            'Connection': 'keep-alive',
            'Upgrade-Insecure-Requests': '1',
            'Content-Type': 'text/html',
            'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36'
    };
        return {
            method: method,
            url: url,
            headers: headers
    };
    };

    getNewSessionIdRequestParams = function (opsaHomeUrl, res) {
        var headers, jar, method, url;
        url = opsaHomeUrl;
        jar = createJar(res, url);
        method = 'GET';
        headers = {
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
            'Accept-Encoding': 'gzip, deflate, sdch',
            'Accept-Language': 'en-US,en;q=0.8,he;q=0.6',
            'Connection': 'keep-alive',
            'Upgrade-Insecure-Requests': '1',
            'Cache-Control': 'max-age=0'
    };
        return {
            method: method,
            url: url,
            jar: jar,
            headers: headers
    };
    };

    getAnomaliesRequestParams = function (opsaHomeUrl, res, xsrfToken) {
        var headers, jar, method, url;
        url = opsaHomeUrl + '/rest/lmt/getIntegratedSystemsDefaults';
        url = opsaHomeUrl + "/rest/getQueryResult?aqlQuery=%5Banomalies%5BattributeQuery(%7Bopsa_collection_anomalies%7D,+%7B%7D,+%7Bi.anomaly_id%7D)%5D()%5D+&endTime=1463654996351&granularity=0&pageIndex=1&paramsMap=%7B%22$drill_dest%22:%22AnomalyInstance%22,%22$drill_label%22:%22opsa_collection_anomalies_description%22,%22$drill_value%22:%22opsa_collection_anomalies_anomaly_id%22,%22$limit%22:%22500%22,%22$interval%22:300,%22$offset%22:0,%22$N%22:5,%22$pctile%22:10,%22$timeoffset%22:0,%22$starttimeoffset%22:0,%22$endtimeoffset%22:0,%22$timeout%22:0,%22$drill_type%22:%22%22,%22$problemtime%22:1463653196351,%22$aggregate_playback_flag%22:null%7D&queryType=generic&startTime=1463651396351&timeZoneOffset=-180&timeout=10&visualType=table";
        jar = createJar(res, url);
        method = 'GET';
        method = 'POST';
        headers = {
            'Accept': 'application/json, text/plain, */*',
            'Accept-Encoding': 'gzip, deflate, sdch',
            'Accept-Language': 'en-US,en;q=0.8,he;q=0.6',
            'Connection': 'keep-alive',
            'Upgrade-Insecure-Requests': '1',
            'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36',
            'XSRFToken': xsrfToken
    };
        return {
            method: method,
            url: url,
            jar: jar,
            headers: headers
    };
    };

    getXSRFRequestParams = function (opsaHomeUrl, res) {
        var headers, jar, method, url;
        method = 'GET';
        url = opsaHomeUrl + "/rest/getXSRFToken";
        headers = {
            'Accept': 'application/json, text/plain, */*',
            'Accept-Encoding': 'gzip, deflate, sdch',
            'Accept-Language': 'en-US,en;q=0.8,he;q=0.6',
            'Connection': 'keep-alive',
            'Upgrade-Insecure-Requests': '1',
            'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36',
            'Cache-Control': 'max-age=0'
    };
        jar = createJar(res, url);
        return {
            method: method,
            url: url,
            jar: jar,
            headers: headers
        };
    };

    invokeOpsaApiHandler = function (res1) {
        var initUrl, opsaHomeUrl, reply;
        if (ongoing) {
            return;
        }
        ongoing = true;
        opsaHomeUrl = 'http://' + hostName;
        reply = "";
        initUrl = getInitialRequestParams(opsaHomeUrl);
        requestp(initUrl.url, initUrl.headers).then((function (res) {
            var secReq;
            secReq = getSecurityRequestParams(opsaHomeUrl, res);
            requestp(secReq.url, secReq.headers, secReq.method, secReq.jar, secReq.form).then((function (res) {
                var newIdReq;
                newIdReq = getNewSessionIdRequestParams(opsaHomeUrl, res);
                return requestp(newIdReq.url, newIdReq.headers, newIdReq.method, secReq.jar).then((function (apiSessionResponse) {
                    var xsrfReq;
                    xsrfReq = getXSRFRequestParams(opsaHomeUrl, apiSessionResponse);
                    return requestp(xsrfReq.url, xsrfReq.headers, xsrfReq.method, xsrfReq.jar).then((function (res) {
                        var AnomaliesAPI, FirstAnomaliesAPI, OpsaAPI, xsrfToken;
                        xsrfToken = res.body;
                        console.log(apiSessionResponse);
                        ongoing = false;
                        OpsaAPI = void 0;
                        AnomaliesAPI = void 0;
                        FirstAnomaliesAPI = void 0;
                        OpsaAPI = function (xsrfToken, jSessionId) {
                            this.xsrfToken = xsrfToken.slice(1, -1);
                            this.jSessionId = jSessionId;
            };
                        AnomaliesAPI = function (xsrfToken, jSessionId, hostName, from, to) {
                            OpsaAPI.call(this, xsrfToken, jSessionId);
                            this.hostName = hostName;
                            this.from = from;
                            this.to = to;
                        };
                        OpsaAPI.prototype.invoke = function () {
                            console.log('invoking API' + this.jSessionId);
                            this.invoker();
                        };
                        AnomaliesAPI.prototype = Object.create(OpsaAPI.prototype);
                        AnomaliesAPI.prototype.constructor = AnomaliesAPI;
                        AnomaliesAPI.prototype.invoker = function () {
                            var anomReq;
                            console.log('Hello, I\'m ' + this.firstName + '. I\'m studying ' + this.subject + '.');
                            anomReq = getAnomaliesRequestParams(opsaHomeUrl, apiSessionResponse, this.xsrfToken);
                            requestp(anomReq.url, anomReq.headers, anomReq.method, anomReq.jar).then((function (anomResponse) {
                                return res1.reply('Displaying Anomalies For Host: ' + scan(JSON.parse(JSON.stringify(anomResponse.body))));
                            }));
                        };
                        AnomaliesAPI.prototype.sayGoodBye = function () {
                            console.log('Goodbye!');
                        };
                        FirstAnomaliesAPI = new AnomaliesAPI(xsrfToken, apiSessionResponse, 'hostName', 'from', 'to');
                        return FirstAnomaliesAPI.invoke();
                    }));
                }));
            }));
        }), function (err) {
            ongoing = false;
            console.error('%s; %s', err.message, opsaHomeUrl);
            console.log('%j', err.res.statusCode);
        });
        return res1.reply('Please wait');
    };

    requestp = function (url, headers, method, jar, form) {
        headers = headers || {};
        method = method || 'GET';
        jar = jar || {};
        form = form || {};
        return new Promise(function (resolve, reject) {
            var reqData;
            reqData = {
                uri: url,
                headers: headers,
                method: method
            };
            if (jar) {
                reqData.jar = jar;
            }
            if (form) {
                reqData.form = form;
            }
            request(reqData, function (err, res, body) {
                if (err) {
                    return reject(err);
                } else if (res.statusCode === 200 || res.statusCode === 302 || res.statusCode === 400) {
                    resolve(res, body);
                } else {
                    ongoing = false;
                    err = new Error('Unexpected status code: ' + res.statusCode);
                    err.res = res;
                    return reject(err);
        }
                resolve(res, body);
            });
        });
    };

  module.exports = function(robot) {
    robot.respond(/top (.*) hosts/i, function(res) {
      return displayHosts(res);
    });
      robot.respond(/alert (.*)/i, function (res) {
      return createMessage(res);
      });
      return robot.respond(/display anomalies for host: (.*)/i, function (res) {
          return invokeOpsaApiHandler(res);
    });
  };

}).call(this);

//# sourceMappingURL=opsa.js.map
