// Generated by CoffeeScript 1.10.0
(function () {
    var Anomalies, Opsa, Utils, request;

    Utils = require('opsaApiUtils.coffee');

    request = require('request');

    Anomalies = require('opsa-anomalies-api.coffee');

    Opsa = require('opsa-general-api.coffee');

    require('request-debug')(request);

    module.exports = function (robot) {
        return robot.respond(/display anomalies for host:?:\s*(.*)/i, function (res) {
            var loginCallback;
            loginCallback = function (xsrfToken, sessionId) {
                var anomaliesAPI, apiCallback;
                anomaliesAPI = new Anomalies.AnomaliesAPI(xsrfToken, sessionId, 'host', 'from', 'to');
                apiCallback = function (body) {
                    var replyText, requestedHost;
                    requestedHost = Utils.getRequestedHost(res);
                    replyText = Anomalies.parseOpsaAnomaliesData(body, requestedHost);
                    res.reply(replyText);
                    Utils.ongoing = false;
                };
                return anomaliesAPI.invoke(apiCallback);
            };
            return Opsa.OpsaAPI.prototype.login(res, loginCallback);
        });
    };

}).call(this);

//# sourceMappingURL=opsa-hubot.js.map
